#pragma config(Motor,  port1,           BRD,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ARMRT,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ARMRB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ARMLT,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           ARMLB,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           CLAWL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           CLAWR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BLD,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  motor[BRD] = 127;
  motor[FRD] = 127;
  motor[BLD] = 127;
  motor[FLD] = 127;

  wait1Msec(2000);

  motor[BRD] = 0;
  motor[FRD] = 0;
  motor[BLD] = 0;
  motor[FLD] = 0;

  }

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                        */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    if (vexRT[Btn6U]){
    	motor[ARMRT] = 127;
			motor[ARMRB] = 127;
			motor[ARMLT] = 127;
			motor[ARMLB] = 127;
    } else if (vexRT[Btn6D]){
  		motor[ARMRT] = -127;
			motor[ARMRB] = -127;
			motor[ARMLT] = -127;
			motor[ARMLB] = -127;
    } else {
  		motor[ARMRT] = 0;
			motor[ARMRB] = 0;
			motor[ARMLT] = 0;
			motor[ARMLB] = 0;
    }

    if (vexRT[Btn5U]){
			motor[CLAWR] = 127;
			motor[CLAWL] = 127;
    } else if (vexRT[Btn5D]){
  		motor[CLAWR] = -127;
			motor[CLAWL] = -127;
    } else {
  		motor[CLAWR] = 0;
			motor[CLAWL] = 0;
    }

    motor[BRD] = vexRT[Ch2];
    motor[FRD] = vexRT[Ch2];

    motor[BLD] = vexRT[Ch3];
    motor[FLD] = vexRT[Ch3];
  }
}
